FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN python3 -m venv /opt/venv-django

RUN /opt/venv-django/bin/pip install pip --upgrade && \
/opt/venv-django/bin/pip install -r requirements.txt

COPY . .

RUN pip install pip --upgrade
RUN pip install -r requirements.txt

RUN chmod +x run.sh

CMD ["./run.sh"]