FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN python3 -m venv /opt/venv-flask

RUN /opt/venv-flask/bin/pip install pip --upgrade && \
/opt/venv-flask/bin/pip install -r requirements.txt

COPY . .

RUN chmod +x run.sh

CMD ["./run.sh"]